import socket
server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server_socket.bind(('localhost', 12345))
server_socket.listen(5)
print("Server is listening...")
print("Nama:    ")
print("NIM: ")
print("No. Telp:    ")
print("Alamat:  ")
print("Provinsi")
while True:
    client_socket, addr = server_socket.accept()
    print(f"Connection from {addr}")
    client_socket.send(b'S E L A M A T  D A T A N G  D I  P E L I T A  I N D O N E S I A')
    client_socket.send(b'Nama: Justyn')
    client_socket.send(b'NIM    : 2155202073')
    client_socket.send(b'No. Telp   : 082288353959')
    client_socket.send(b'Alamat : Jl. Kotabaru No.38B')
    client_socket.send(b'Provinsi   : Riau')
    client_socket.close()